name: Build & run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: .
  BINARY_FILE_PATH: bin
  BUILD_CONFIGURATION: Release
  PLATFORM: x64

permissions:
  actions: read #for TAServers/vcpkg-cache
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      run: nuget restore ${{ env.SOLUTION_FILE_PATH }}

    - name: Restore vcpkg cache
      id: vcpkg-cache
      uses: TAServers/vcpkg-cache@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Integrate vcpkg
      run: |
        vcpkg integrate install

    - name: Build
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      run: |
        msbuild ${{ env.SOLUTION_FILE_PATH }} -m -p:Configuration=${{ env.BUILD_CONFIGURATION }} -p:Platform=${{ env.PLATFORM }} -p:OutDir="${{ github.workspace }}\${{ env.BINARY_FILE_PATH }}\"
      # env:
        # VCPKG_BINARY_SOURCES: "clear;files,${{ steps.vcpkg-cache.outputs.path }},readwrite"

    - name: Run tests
      run: |
        & "${{ env.BINARY_FILE_PATH }}\Tests.exe"

    - name: Upload artifact
      id: upload_artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-x64
        path: ${{ env.BINARY_FILE_PATH }}\SoundRemote.exe
        compression-level: 9

    # - name: Create "Artifact SHA-256" notice
      # run: echo "::notice title=Artifact SHA-256::${{ steps.upload_artifact.outputs.artifact-digest }}"
